- name: Configure Search Head Cluster Secret
  community.general.ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: shclustering
    option: pass4SymmKey
    value: "{{ shcluster_secret }}"
    owner: splunk
    group: splunk
    mode: "0644"
    no_extra_spaces: true
    backup: true
  notify:
    - Restart Splunk