---
- name: Create a volume for Heavy Forwarder data
  community.docker.docker_volume:
    name: splunk_hf_data

- name: Create Splunk Heavy Forwarder container
  community.docker.docker_container:
    name: splunk-heavy-forwarder
    image: splunk/splunk:latest
    state: started
    restart_policy: unless-stopped
    pull: true

    published_ports:
      - "8000:8000"
      - "8089:8089"
      - "9997:9997"

    volumes:
      - "splunk_hf_data:/opt/splunk"

    env:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: "{{ splunk_admin_password }}"

- name: Check Splunk Heavy Forwarder status
  community.docker.docker_container_exec:
    container: splunk-heavy-forwarder
    command: /opt/splunk/bin/splunk status
  register: splunk_status
  retries: 12
  delay: 10
  until:
    - splunk_status.stdout is defined
    - "'splunkd is running' in splunk_status.stdout"
  changed_when: false


# - name: Connect Heavy Forwarder to Deployment Server
#   ansible.builtin.command:
#     argv:
#       - "{{ splunk_home }}/bin/splunk"
#       - set
#       - deploy-poll
#       - "{{ deployment_server_uri }}"
#       - -auth
#       - "{{ splunk_admin_user }}:{{ splunk_admin_password }}"
#   become: true
#   become_user: splunk
#   register: deployment_server_result
#   changed_when: deployment_server_result.rc == 0
#   no_log: false
#   notify: Restart Splunk

# - name: Connect Heavy Forwarder to License Manager
#   ansible.builtin.command:
#     argv:
#       - "{{ splunk_home }}/bin/splunk"
#       - edit
#       - licenser-localpeer
#       - -manager_uri
#       - "https://{{ license_manager_uri }}"
#       - -auth
#       - "{{ splunk_admin_user }}:{{ splunk_admin_password }}"
#   become: true
#   become_user: splunk
#   register: license_manager_result
#   changed_when: license_manager_result.rc == 0
#   no_log: true
#   when: use_remote_license_manager | default(false) | bool
#   notify: Restart Splunk