[cluster_manager]
cluster-manager.dev.kiranpanchavati.online

[indexers]
indexer1.dev.kiranpanchavati.online
indexer2.dev.kiranpanchavati.online

[deployment_server]
deployment-server.dev.kiranpanchavati.online

[heavy_forwarders]
heavyforwarder.dev.kiranpanchavati.online