[cluster_manager]
cluster-manager.dev.kiranpanchavati.online

[indexers]
indexer1.dev.kiranpanchavati.online
indexer2.dev.kiranpanchavati.online

[search_heads]
search-head1.dev.kiranpanchavati.online
search-head2.dev.kiranpanchavati.online
search-head3.dev.kiranpanchavati.online

[deployer]
deployer.dev.kiranpanchavati.online

[deployment_server]
deployment-server.dev.kiranpanchavati.online

[license_managers]
license-master.dev.kiranpanchavati.online

[monitoring_console]
monitoring-console.dev.kiranpanchavati.online

[heavy_forwarders]
heavyforwarder.dev.kiranpanchavati.online