- name: Create serverclass.conf file
  ansible.builtin.copy:
    dest: "{{ splunk_home }}/etc/system/local/serverclass.conf"
    owner: splunk
    group: splunk
    mode: '0644'
    content: |
      [serverClass:dev_infrateam_linux]
      whitelist.0 = *

      [serverClass:dev_infrateam_linux:app:infra_linux_custom_app]
      restartSplunkd = true
  notify: Restart Splunk

- name: Create new custom app directory
  ansible.builtin.file:
    path: "{{ splunk_home }}/etc/deployment-apps/infra_linux_custom_app"
    state: directory
    owner: splunk
    group: splunk
    mode: '0755'

- name: Create local directory for the app
  ansible.builtin.file:
    path: "{{ splunk_home }}/etc/deployment-apps/infra_linux_custom_app/local"
    state: directory
    owner: splunk
    group: splunk
    mode: '0755'


- name: Create default directory for the app
  ansible.builtin.file:
    path: "{{ splunk_home }}/etc/deployment-apps/infra_linux_custom_app/default"
    state: directory
    owner: splunk
    group: splunk
    mode: '0755'

- name: Create app.conf file
  ansible.builtin.copy:
    dest: "{{ splunk_home }}/etc/deployment-apps/infra_linux_custom_app/default/app.conf"
    owner: splunk
    group: splunk
    mode: '0644'
    content: |
      [launcher]
      author = Splunk
      description = Custom app for deployment server
      version = 1.0.0

      [package]
      id = infra_linux_custom_app

- name: Create inputs.conf file in the local directory 
  ansible.builtin.copy:
    dest: "{{ splunk_home }}/etc/deployment-apps/infra_linux_custom_app/local/inputs.conf"
    owner: splunk
    group: splunk
    mode: '0644'
    content: |
      [monitor:///var/log/secure]
      sourcetype = infra_linux_custom_sourcetype
      index = infra_linux_custom_index
      disabled = false 

- name: Create outputs.conf file in the local directory
  ansible.builtin.copy:
    dest: "{{ splunk_home }}/etc/deployment-apps/infra_linux_custom_app/local/outputs.conf"
    owner: splunk
    group: splunk
    mode: '0644'
    content: |
      [tcpout]
      defaultGroup = indexergroup

      [tcpout:indexergroup]
      server = {{ indexer_1_uri }}, {{ indexer_2_uri }}

- name: Reload deployment server to push app
  ansible.builtin.command: "{{ splunk_home }}/bin/splunk reload deploy-server -auth {{ splunk_admin_user }}:{{ splunk_admin_password }}"