---
- name: Download Docker repository file
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: "0644"

- name: Install Docker packages
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3-pip
    state: present

- name: Install Docker Python SDK
  ansible.builtin.pip:
    name:
      - docker
    executable: pip3

- name: Start and enable containerd
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true

- name: Start and enable Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Verify Docker
  ansible.builtin.command:
    cmd: docker info
  register: docker_info
  changed_when: false