---
- name: Install Docker on Deployment Server
  hosts: deployment_server
  become: true

  roles:
    - common

- name: Deploy Splunk Deployment Server
  hosts: deployment_server
  become: true

  roles:
    - deployment-server