---
- name: Install Docker on Heavy Forwarder
  hosts: heavy_forwarders
  become: true

  roles:
    - common

- name: Deploy Splunk Heavy Forwarder
  hosts: heavy_forwarders
  become: true

  roles:
    - heavy-forwarder